---
title: "Course Project 1"
author: "Melanie Carlson"
date: "Sunday, June 07, 2015"
output: html_document
---

Read in the Data, Convert Dates and subset it for appropriate dat range:

```{r}
setwd("C:/Users/Melanie/Desktop/R Code Class/exploratory data")
DataComplete <- read.csv("C:/Users/Melanie/Desktop/R Code Class/exploratory data/household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
DataComplete$Date <- as.Date(DataComplete$Date, format="%d/%m/%Y")
FinalData <- subset(DataComplete, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(DataComplete)
```

Create Plot #1:

```{r}
hist(FinalData$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
```

Convert Times and Create Plot #2:

```{r}
datetime <- paste(as.Date(FinalData$Date), FinalData$Time)
FinalData$Datetime <- as.POSIXct(datetime)
plot(FinalData$Global_active_power~FinalData$Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
```

Create Plot #3:
```{r}
 
with(FinalData, {
    plot(Sub_metering_1~datetime, type="l",
         ylab="Global Active Power (kilowatts)", xlab="")
    lines(Sub_metering_2~datetime,col='Red')
    lines(Sub_metering_3~datetime,col='Blue')
})
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, 
       legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
```

Create Plot #4:
```{r}
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(FinalData, {
    plot(Global_active_power~Datetime, type="l", 
         ylab="Global Active Power (kilowatts)", xlab="")
    plot(Voltage~Datetime, type="l", 
         ylab="Voltage (volt)", xlab="")
    plot(Sub_metering_1~Datetime, type="l", 
         ylab="Global Active Power (kilowatts)", xlab="")
    lines(Sub_metering_2~Datetime,col='Red')
    lines(Sub_metering_3~Datetime,col='Blue')
    legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",
           legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
    plot(Global_reactive_power~Datetime, type="l", 
         ylab="Global Rective Power (kilowatts)",xlab="")
```